"""
Build script: creates a standalone Windows .exe using PyInstaller.

Usage (run once to set up, then build):
    pip install pyinstaller
    python build_exe.py

The output will be in dist/IEEE_Early_Access/
The final executable: dist/IEEE_Early_Access/IEEE_Early_Access.exe
"""

import subprocess
import sys
import shutil
from pathlib import Path

HERE = Path(__file__).parent.resolve()
DIST = HERE / "dist"
BUILD = HERE / "build"
SPEC = HERE / "IEEE_Early_Access.spec"


def main() -> None:
    # ── 1. Make sure PyInstaller is available ──────────────────────────────────
    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print("PyInstaller not found. Installing…")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "pyinstaller"])

    # ── 2. Clean previous artefacts ────────────────────────────────────────────
    for d in (DIST, BUILD):
        if d.exists():
            shutil.rmtree(d)
            print(f"Removed {d}")

    # ── 3. Write the .spec file ────────────────────────────────────────────────
    spec_content = r"""# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_exe.py — edit build_exe.py, not this file.

import sys
from pathlib import Path

HERE = Path(SPEC).parent

a = Analysis(
    [str(HERE / 'app.py')],
    pathex=[str(HERE)],
    binaries=[],
    datas=[
        # Bundle the templates/ folder so Flask can find index.html at runtime
        (str(HERE / 'templates'), 'templates'),
        # Bundle config.py so users can inspect / edit defaults (optional)
        (str(HERE / 'config.py'), '.'),
    ],
    hiddenimports=[
        # Flask / Werkzeug dynamic imports that PyInstaller misses
        'flask',
        'jinja2',
        'jinja2.ext',
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.debug',
        'werkzeug.routing',
        'werkzeug.middleware',
        'werkzeug.middleware.proxy_fix',
        'click',
        'itsdangerous',
        # requests
        'requests',
        'urllib3',
        'charset_normalizer',
        'certifi',
        'idna',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='IEEE_Early_Access',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,          # keep console so users see the "Serving at …" URL
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='IEEE_Early_Access',
)
"""
    SPEC.write_text(spec_content, encoding="utf-8")
    print(f"Written: {SPEC}")

    # ── 4. Run PyInstaller ─────────────────────────────────────────────────────
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--clean",
        str(SPEC),
    ]
    print("\nRunning PyInstaller…")
    print(" ".join(cmd))
    subprocess.check_call(cmd, cwd=HERE)

    # ── 5. Post-build summary ──────────────────────────────────────────────────
    exe_path = DIST / "IEEE_Early_Access" / "IEEE_Early_Access.exe"
    if exe_path.exists():
        size_mb = exe_path.stat().st_size / 1_048_576
        print(f"\n{'='*55}")
        print(f"  Build successful!")
        print(f"  Executable : {exe_path}")
        print(f"  Size       : {size_mb:.1f} MB")
        print(f"  Folder     : {exe_path.parent}")
        print(f"{'='*55}")
        print("\nTo distribute: zip the entire  dist/IEEE_Early_Access/  folder.")
        print("Recipients double-click  IEEE_Early_Access.exe  — no Python needed.")
    else:
        print("\nBuild may have failed — exe not found at expected path.")
        sys.exit(1)


if __name__ == "__main__":
    main()
